version=1.1.6
mod_name=Classic Pipes
mod_id=classicpipes
group=jagm.classicpipes
mod_author=Jagm
license=CC BY-NC-SA 4.0
credits=Beta testers: Tipsy, Sketti, and Charlie. Translators: Filmorae (Chinese), Hamutaromaru (Japanese), pGabrielVP & PrincessStellar (Portuguese), AstardGrimoire (Russian). Inspired by Buildcraft by SpaceToad and Logistics Pipes by Krapht. Built on Jaredlll08's MultiLoader.
description=A simple but versatile item transport system.
logo=logo.png
issues=https://github.com/J4gm/classicpipes/issues

java_version=25
minecraft_version=26.2
minecraft_version_range=[26.2, 26.3)

# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-2

# https://fabricmc.net/develop/
fabric_version=0.155.2+26.2
fabric_loader_version=0.19.3

# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=65.0.9
forge_loader_version_range=[65,)

# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.2.0.32-beta
neoforge_loader_version_range=[4,)

# https://maven.blamejared.com/mezz/jei/
jei_minecraft=26.2
jei_version=30.13.0.86

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
