version=1.1.6
mod_name=Classic Pipes
mod_id=classicpipes
group=jagm.classicpipes
mod_author=Jagm
license=CC BY-NC-SA 4.0
credits=Beta testers: Tipsy, Sketti, and Charlie. Translators: Filmorae (Simplified Chinese), Hamutaromaru (Japanese), pGabrielVP & PrincessStellar (Brazilian Portuguese), AstardGrimoire (Russian). Inspired by Buildcraft by SpaceToad and Logistics Pipes by Krapht. Built on Jaredlll08's MultiLoader.
description=A simple but versatile item transport system.
logo=logo.png
issues=https://github.com/J4gm/classicpipes/issues

java_version=25
minecraft_version=26.1.2
minecraft_version_range=[26.1.2, 26.2)

# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1

# https://fabricmc.net/develop/
fabric_version=0.150.0+26.1.2
fabric_loader_version=0.19.3

# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=64.0.8
forge_loader_version_range=[64,)

# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.1.2.71
neoforge_loader_version_range=[4,)

# https://maven.blamejared.com/mezz/jei/
jei_minecraft=26.1.2
jei_version=29.6.2.31

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
